define([], ()->

  CHALLENGESENT_STATE:"CHALLENGESENT"
  CHALLENGED_STATE:"CHALLENGED"
  READY_STATE:"READY"
  CREATED_STATE:"CREATED"
  PLAYING_STATE:"PLAYING"

  LogEvents:
    GAMECREATED:"GAMECREATED"
    USERSTATUSCHANGED:"USERSTATUSCHANGED"
    CHALLENGEISSUED:"CHALLENGEISSUED"

  MoveTypes:
    PLAYER_MOVE:"PLAYER_MOVE"
    NEW_TURN:"NEW_TURN"
)

