define([], ()->
  CHALLENGED_STATE:"CHALLENGED"
  READY_STATE:"READY"
  CREATED_STATE:"CREATED"

  LogEvents:
    GAMECREATED:"GAMECREATED"
    USERSTATUSCHANGED:"USERSTATUSCHANGED"
    CHALLENGEISSUED:"CHALLENGEISSUED"
)

