define([], ()->

  CHALLENGESENT_STATE:"CHALLENGESENT"
  CHALLENGED_STATE:"CHALLENGED"
  READY_STATE:"READY"
  CREATED_STATE:"CREATED"
  PLAYING_STATE:"PLAYING"

  LogEvents:
    GAMECREATED:"GAMECREATED"
    USERSTATUSCHANGED:"USERSTATUSCHANGED"
    CHALLENGEISSUED:"CHALLENGEISSUED"
)

